### Import all necessary libraries

In [25]:
import pandas as pd
import os
import numpy as np

# Data Processing
We shall first take a look at the data and understand the values

In [26]:
# Import the csv file as a pandas dataframe
path = os.getcwd()
scraped_data_path = os.path.join(path, "scraped_data.csv")
df = pd.read_csv(scraped_data_path)
print(df.shape)

(28813, 14)

In [27]:
df.head(5)

,Address,Property Name,Property Type,Bedrooms,Bathrooms,Asking Price,Size,PSF,Age,Tenure,No. of Units,District,Amenities,Link
0,2 Dunman Road (439188),Grand Dunman,Apartment,4+1,3,"$3,764,000","1,679 sqft","$2,242 psf",Not Available,LEASEHOLD/99 years,1008,D15 - East Coast / Marine Parade,"{'Primary Schools': [{'Kong Hwa': '0.41 km'}, ...",https://www.srx.com.sg/listings/101051671/for-...
1,Shelford Road,Shelford View,Condominium,5,4,"$10,000,000","5,134 sqft","$1,948 psf",41,FREEHOLD,20,D11 - Newton / Novena,"{'Primary Schools': [{""Raffles Girls' Primary""...",https://www.srx.com.sg/listings/101439641/for-...
2,Hillview Rise,Hillhaven,Apartment,2,2,"$1,387,352",678 sqft,"$2,046 psf",Not Available,LEASEHOLD/99 years,341,D23 - Dairy Farm / Bukit Panjang / Choa Chu Kang,{'Primary Schools': [{'Chij Our Lady Queen Of ...,https://www.srx.com.sg/listings/101369031/for-...
3,60H Kent Ridge Hill Residences (117321),Kent Ridge Hill Residences,Apartment,1,1,"$1,030,000 (Negotiable)",474 sqft,"$2,173 psf",1,LEASEHOLD/99 years,548,D5 - Buona Vista / West Coast / Clementi New Town,"{'Primary Schools': [], 'Secondary Schools': [...",https://www.srx.com.sg/listings/100989811/for-...
4,Marina Way,Marina One Residences,Apartment,1,1,"$1,630,000",700 sqft,"$2,329 psf",7,LEASEHOLD/99 years,1042,D1 - Boat Quay / Raffles Place / Marina,{'Primary Schools': [{'Cantonment Primary': '1...,https://www.srx.com.sg/listings/95119111/for-s...

## Conducting Feature Selection
Removing the Link Column as it does not provide any useful information

In [28]:
# The Link column does not look useful as a feature
df.drop('Link', axis=1)

,Address,Property Name,Property Type,Bedrooms,Bathrooms,Asking Price,Size,PSF,Age,Tenure,No. of Units,District,Amenities
0,2 Dunman Road (439188),Grand Dunman,Apartment,4+1,3,"$3,764,000","1,679 sqft","$2,242 psf",Not Available,LEASEHOLD/99 years,1008,D15 - East Coast / Marine Parade,"{'Primary Schools': [{'Kong Hwa': '0.41 km'}, ..."
1,Shelford Road,Shelford View,Condominium,5,4,"$10,000,000","5,134 sqft","$1,948 psf",41,FREEHOLD,20,D11 - Newton / Novena,"{'Primary Schools': [{""Raffles Girls' Primary""..."
2,Hillview Rise,Hillhaven,Apartment,2,2,"$1,387,352",678 sqft,"$2,046 psf",Not Available,LEASEHOLD/99 years,341,D23 - Dairy Farm / Bukit Panjang / Choa Chu Kang,{'Primary Schools': [{'Chij Our Lady Queen Of ...
3,60H Kent Ridge Hill Residences (117321),Kent Ridge Hill Residences,Apartment,1,1,"$1,030,000 (Negotiable)",474 sqft,"$2,173 psf",1,LEASEHOLD/99 years,548,D5 - Buona Vista / West Coast / Clementi New Town,"{'Primary Schools': [], 'Secondary Schools': [..."
4,Marina Way,Marina One Residences,Apartment,1,1,"$1,630,000",700 sqft,"$2,329 psf",7,LEASEHOLD/99 years,1042,D1 - Boat Quay / Raffles Place / Marina,{'Primary Schools': [{'Cantonment Primary': '1...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
28808,Meyer Mansion,Meyer Mansion,Apartment,3,2,"$3,580,000","1,109 sqft","$3,228 psf",Not Available,FREEHOLD,200,D15 - East Coast / Marine Parade,{'Primary Schools': [{'Tanjong Katong Primary'...
28809,Jalan Tembusu,Tembusu Grand,Condominium,2+1,2,"$2,102,000",883 sqft,"$2,381 psf",Not Available,LEASEHOLD/99 years,638,D15 - East Coast / Marine Parade,{'Primary Schools': [{'Tanjong Katong Primary'...
28810,The Oceanfront @ Sentosa Cove,The Oceanfront @ Sentosa Cove,Condominium,4,5,"$7,980,000","3,300 sqft","$2,418 psf",14,LEASEHOLD/99 years,264,D4 - Sentosa / Harbourfront,"{'Primary Schools': [], 'Secondary Schools': [..."
28811,Thiam Siew Avenue,The Continuum,Apartment,3,3,"$3,473,000","1,302 sqft","$2,667 psf",Not Available,FREEHOLD,816,D15 - East Coast / Marine Parade,"{'Primary Schools': [{'Kong Hwa': '0.7 km'}, {..."
28812,Parc Emily,Parc Emily,Condominium,2,3,"$4,180,000 (Negotiable)","1,733 sqft","$2,412 psf",16,FREEHOLD,295,D9 - Orchard / River Valley,"{'Primary Schools': [{""St. Margaret's Primary""..."

## Data Cleaning

In [29]:
df['Age'].replace("Not Available", np.nan, inplace=True)
df.head(5)

,Address,Property Name,Property Type,Bedrooms,Bathrooms,Asking Price,Size,PSF,Age,Tenure,No. of Units,District,Amenities,Link
0,2 Dunman Road (439188),Grand Dunman,Apartment,4+1,3,"$3,764,000","1,679 sqft","$2,242 psf",NaN,LEASEHOLD/99 years,1008,D15 - East Coast / Marine Parade,"{'Primary Schools': [{'Kong Hwa': '0.41 km'}, ...",https://www.srx.com.sg/listings/101051671/for-...
1,Shelford Road,Shelford View,Condominium,5,4,"$10,000,000","5,134 sqft","$1,948 psf",41,FREEHOLD,20,D11 - Newton / Novena,"{'Primary Schools': [{""Raffles Girls' Primary""...",https://www.srx.com.sg/listings/101439641/for-...
2,Hillview Rise,Hillhaven,Apartment,2,2,"$1,387,352",678 sqft,"$2,046 psf",NaN,LEASEHOLD/99 years,341,D23 - Dairy Farm / Bukit Panjang / Choa Chu Kang,{'Primary Schools': [{'Chij Our Lady Queen Of ...,https://www.srx.com.sg/listings/101369031/for-...
3,60H Kent Ridge Hill Residences (117321),Kent Ridge Hill Residences,Apartment,1,1,"$1,030,000 (Negotiable)",474 sqft,"$2,173 psf",1,LEASEHOLD/99 years,548,D5 - Buona Vista / West Coast / Clementi New Town,"{'Primary Schools': [], 'Secondary Schools': [...",https://www.srx.com.sg/listings/100989811/for-...
4,Marina Way,Marina One Residences,Apartment,1,1,"$1,630,000",700 sqft,"$2,329 psf",7,LEASEHOLD/99 years,1042,D1 - Boat Quay / Raffles Place / Marina,{'Primary Schools': [{'Cantonment Primary': '1...,https://www.srx.com.sg/listings/95119111/for-s...

In [30]:
# Checking nan values
# Check for NaN values in each column
nan_counts_per_column = df.isna().sum()
print("NaN counts per column:")
print(nan_counts_per_column)

df = df.dropna()

NaN counts per column:
Address              0
Property Name        0
Property Type        0
Bedrooms             0
Bathrooms            0
Asking Price       124
Size                 0
PSF                  0
Age              11706
Tenure               0
No. of Units         0
District             0
Amenities            0
Link                 0
dtype: int64